### ISSUE TITLE
Save PPO logStd for Continuous, not Discrete, version

### ISSUE THREAD

**Issue by schnecki** [AugustUnderground/edelwace#1]
Hi,

was reading your code and found this. Doesn't look right to me. 

https://github.com/AugustUnderground/edelwace/blob/7607974adc0f033dbab95b9293f54429d1225a95/src/PPO.hs#L149

Best Manuel

**Comment by AugustUnderground** [comment]
Should be `/=` as this only makes sense for continuous spaces. Thanks for pointing it out. Since the deprecation of ace I'm not working with this anymore, but I'll fix it when I get the time.
